### ISSUE TITLE
Implementing TIDE in neuralforecast

### ISSUE THREAD

**Issue by valeman** [Nixtla/neuralforecast#970] opened 2024-04-15 10:19 UTC
### Description

Did the team consider implementing TIDE? is seems to be getting a lot of traction recently confirming its performance vis-a-vis the one in TIDE paper and it has been also implemented in Darts. Would be great to have it in neuralforecast.

Long-term Forecasting with TiDE: Time-series Dense Encoder https://arxiv.org/abs/2304.08424

**Comment by elephaint** [comment] 2024-04-15 14:06
Sure, we'll have a look!

**Comment by candalfigomoro** [comment] 2024-04-22 10:19
Duplicate of Issue #610

**Closed** 2024-05-06 17:21 UTC
Labels: enhancement, feature
